### ISSUE TITLE
Peer review Project 3

### ISSUE THREAD

**Issue by pswargam** [airavata-courses/alpha#50]

**Comment by pswargam** [comment]
Hi Hardik,

I am unable to make requests. I am seeing below errors

org.apache.http.conn.HttpHostConnectException: Connect to 149.165.169.102:8080 [/149.165.169.102] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl$JMeterDefaultHttpClientConnectionOperator.connect(HTTPHC4Impl.java:331)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)

**Comment by siddharthpathak** [comment]
How many threads you did you use? It might happen because large number of threads on your machine and it not able to create as many.
